#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

set -e
set -x

cmd=`jq -r .command config.json`
case "$cmd" in

    dipy_track_pft)
        cat > script.sh <<EOF
#!/bin/bash
$cmd --force \
    --out_dir $(pwd) \
    --step_size $(jq -r .step_size config.json) \
    --seed_density $(jq -r .seed_density config.json) \
    --pmf_threshold $(jq -r .pmf_threshold config.json) \
    --max_angle $(jq -r .max_angle config.json) \
    --pft_back $(jq -r .pft_back config.json) \
    --pft_front $(jq -r .pft_front config.json) \
    --pft_count $(jq -r .pft_count config.json) \
    $(jq -r .peaks config.json) $(jq -r .wm config.json) $(jq -r .gm config.json) $(jq -r .csf config.json) $(jq -r .seed config.json)
EOF
        ;;
    *)
        echo "invalid command: $cmd"
        exit 1
esac

chmod +x script.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:1.1.1 ./script.sh

echo "done"